# Generated by Django 4.2.4 on 2023-08-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_meme_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
