# Generated by Django 4.2.4 on 2023-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_meme_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('box_count', models.IntegerField()),
            ],
        ),
    ]
