# Generated by Django 4.2.4 on 2023-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('you_and_meme_backend_app',
         '0003_profile_alter_comment_user_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
